caper/caper/views.py
Fix tested locally with contino data. Addresses issue in the screenshot below:
=> bugfix to views.py

caper/caper/sample_plot.py, caper/caper/urls.py, caper/caper/views.py, caper/templates/pages/create_project.html, caper/templates/pages/index.html, caper/templates/pages/profile.html, caper/templates/pages/project.html, caper/templates/pages/sample.html
created fixes for issues 34 (not 35), 42, and 49. Also deals with 51, 52, and 53
=> added new download and updates to ui

README.md, caper/caper/sample_plot.py
=> address colored bar selection and improve CN selection capabilities

purge-local-db.py
Edwin can you do a test to make sure this works on your end?
Thanks,
Forrest
=> create a purge local db script

caper/caper/StackedBarChart.py, caper/caper/classification.py, caper/caper/views.py
Improve performance of code for gathering data for project page plots. Reduces loadtime for CCLE project from 15s to 1-2s.
=> performance improvements for opening a project page

caper/caper/views.py
After multiple rounds of testing this was the most optimal fix for improving project download. There still seems to be some level of reading on the side of Django, but I want to test it on the server to see how it fairs. I got an average of 2-3 min for the 3GB CCLE project.
=> added proper streaming fix with chunking for project download

caper/caper/StackedBarChart.py, caper/caper/classification.py
fix sample name pileups (#115) and other hover issues
=> tweaks to stacked bar chart and pie chart

caper/caper/views.py, caper/templates/pages/project.html
Forrest, most of what was needed was already there commented out as you said.  Please review
=> Add edit button back to project page for project members

caper/caper/views.py, caper/templates/includes/header.html, caper/templates/pages/create_project.html
- When user doesn't upload a project file, clicking the "create project" button will display an alert on the top of the page saying: "No File Selected, Please select a file using the "Choose File" button at the bottom of the form and try again." 
- Changes will be seen on the "create project" page. 
- Also includes a change in headers.html which will fix an issue where when the window is narrow and the navbar button shows up but the navbar items don't show up. The navbar items will show up now.
=> Changes for issue 137

caper/templates/pages/create_project.html
Just adds a line of text to the project creation page. Tested locally without issues.
=> add blurb of text guiding users with large uploads to use Aggregator

caper/caper/views.py
moved uuid.uuid4().hex as default parameter, allowing API to generate an ID first so it won't run into a file not found error for POST.
=> update API to use tmp_id for file uploads

caper/caper/views.py, caper/templates/pages/edit_project.html
been tested already by Jens and Edwin on the dev server
=> Issues 151 180

caper/caper/views.py
- Hangs up the aggregator when upload is complete, sends project extraction to another thread. 
- Allows multipart POST upload from API, so files larger than 2GB will post successfully.
=> Issue 159 v2

README.md, caper/caper/views.py, caper/templates/includes/footer.html, caper/templates/pages/create_project.html, caper/templates/pages/index.html
Just adds documentation and textual changes to the site. Tested locally without issues.
=> documentation and site text updates

caper/templates/includes/footer.html, caper/templates/pages/index.html
- Add text to footer to inform users results are hosted under Creative Commons v4 (#203)
- Center footer on page and lighten font
- Add small border around tabs on main page and make unselected tab text blue to indicate is clickable.
=> update footer and adjust styling of main page table tabs

.gitignore, caper/caper/forms.py, caper/caper/site_stats.py, caper/templates/includes/footer.html, caper/templates/pages/sample.html
project creation/deletion were not properly working. This fixes the issues Edwin and I observed when attempting to deploy last week.
Also adds ability to click sample name in table and show plot.
Tested locally without issues.
=> bugfixes to site stats & text tweaks

caper/caper/views.py, caper/templates/pages/admin_stats.html, caper/templates/pages/index.html
Reviewer please confirm that public and private projects created before using this branch can still be loaded.
=> bugfix to FINISHED? for existing projects

caper/caper/views.py, caper/weekly-report.py
small bug fixes to usage stats
=> fix bugs in dev testing

caper/weekly-report.py
Had to make some small fixes during implementation on dev. These were the changes that had to be made
=> fixed bugs when on dev

caper/caper/views.py
suppressed logging so the stdout isn't filled with datetime errors.
=> added different formats to try parsing datetime

caper/caper/views.py
fixes project creation for small files
=> Remove problematic debug line

caper/caper/settings.py, caper/caper/views.py, start-server.sh
remove the _SECRET from the settings EMAIL_HOST_USER and EMAIL_HOST_P…ASSWORD since the django.core.email plugin required the original names without _SECRET
=> fix for django.core.email use

caper/templates/pages/project.html
- caused by some testing code I put in at the top. Removed and the search came back.
=> Update project.html to fix missing search functionality

caper/caper/views.py
fixes previous project version download on prod #261
=> fix missing linkid

caper/caper/settings.py, caper/caper/user_preferences.py
added EMAIL_HOST_USER_SECRET, and fixed typo in user_pref.py
=> Edwin5588 patch 1

caper/caper/utils.py, caper/caper/views.py
new function in utils.py querys the db which opens a cursor, then closes that cursor and returns the projects.
=> Added a new function that querys DB and closes connection

caper/caper/aggregator_main.py, caper/caper/forms.py, caper/caper/settings.py, caper/caper/views.py, caper/templates/pages/create_project.html, caper/templates/pages/edit_project.html
=> Aggregator integration

caper/templates/base.html, caper/templates/includes/header.html, caper/templates/pages/create_project.html, caper/templates/pages/index.html
removing the row in base.html & index.html  to get rid of horizontal scroll
=> quick CSS fix, removing the horizontal scroll

caper/caper/extra_metadata.py, caper/caper/sample_plot.py, caper/caper/site_stats.py, caper/caper/utils.py, caper/caper/views.py
- Attempts to improve issues with MongoDB connection resulting in 502 errors
- Shift some loops into obvious list comprehensions 
- Fix to previous utilities that updated site stats on project privacy update
- remove unused imports
=> mongodb connection, loops, site statistics

caper/caper/search.py, caper/caper/views.py, caper/templates/includes/header.html, caper/templates/includes/searchbox.html, caper/templates/pages/gene_search.html
When clicking header after opening search, the metadata search would open. This pops the search out as it's own window.
Also merged tissue and cancer type search boxes per Vineet request #327 
Improved table formatting when tons of genes are present
=> Bugfix to search menu clicking

caper/caper/views.py
=> fix local import issue

README.md, caper/caper/coamp_graph.py, caper/caper/neo4j_utils.py, caper/static/css/coamp.css, caper/static/js/coamp_frontend.js, caper/templates/pages/visualizer.html
- add new significance testing calculations
- removed print statements clogging the logs
- table download bugfixes
- UI tweaks
=> Co-amp graph improvements

caper/caper/coamp_graph.py, caper/caper/views.py, caper/static/css/coamp.css, caper/static/js/coamp_frontend.js, caper/templates/pages/visualizer.html
Adds a box to show what projects are included in the co-amp analysis
=> Add list of projects to co-amp page
